steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'GEMINI_API_KEY=$_GEMINI_API_KEY'
      - '-t'
      - '$_IMAGE_NAME'
      - '.'
images:
  - '$_IMAGE_NAME'
substitutions:
  _GEMINI_API_KEY: 'CHANGE_ME' # Pass this via command line
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/aegis-482716/aegis/aegis' # Default tag
